openapi: 3.0.0
info:
  title: Microservicio de Gestión de Inventario
  description: API para gestionar habitaciones y su estado en un sistema de inventario.
  version: 1.0.0
  contact:
    name: Equipo de Desarrollo
    email: soporte@ejemplo.com

servers:
  - url: http://localhost:4000/api
    description: Servidor de desarrollo local

paths:
  /rooms:
    post:
      summary: Registrar una nueva habitación
      description: Crea un nuevo registro de habitación en el sistema de inventario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_number:
                  type: integer
                  example: 101
                room_type:
                  type: string
                  example: Deluxe
                status:
                  type: string
                  enum: [available, maintenance]
                  example: available
      responses:
        201:
          description: Habitación creada exitosamente.
        500:
          description: Error interno del servidor.

  /rooms/{id}:
    patch:
      summary: Actualizar el estado de una habitación
      description: Modifica el estado de una habitación existente (e.g., disponible, mantenimiento).
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la habitación.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [available, maintenance]
                  example: maintenance
      responses:
        200:
          description: Estado de la habitación actualizado exitosamente.
        404:
          description: Habitación no encontrada.
        500:
          description: Error interno del servidor.
